import picuture from "../../public/WhatsApp Image 2026-01-07 at 11.05.58 PM.jpeg";

export const products = [
  {
    id: "af-500",
    brand: "Absolutely Not",
    brandType: "own",
    tag: "Our Brand",
    tagColor: "bg-sky-500",
    img: picuture,
    name: "Absolutely Not 500ml",
    des: "Aqua Forge's signature water bottle. Crisp, clean, and crafted for everyday hydration. BPA-free with a leak-proof lid.",
    size: "500ml",
    pricePerBottle: 36,
    bottlesPerCarton: 12,
    get pricePerCarton() {
      return this.pricePerBottle * this.bottlesPerCarton;
    },
    minCarton: 6,
    get price() {
      return this.pricePerCarton * this.minCarton;
    },
    category: "Own Brand",
  },
  {
    id: "af-1500",
    brand: "Absolutely Not",
    brandType: "own",
    tag: "Our Brand",
    tagColor: "bg-sky-500",
    img: picuture,
    name: "Absolutely Not 1500ml",
    des: "The big one. Perfect for long days, gym sessions, and staying fully hydrated. Same premium quality, larger capacity.",
    size: "1500ml",
    pricePerBottle: 62,
    bottlesPerCarton: 6,
    get pricePerCarton() {
      return this.pricePerBottle * this.bottlesPerCarton;
    },
    minCarton: 6,
    get price() {
      return this.pricePerCarton * this.minCarton;
    },
    category: "Own Brand",
  },
  {
    id: "cb-500",
    brand: "Client Brand",
    brandType: "custom",
    tag: "Custom",
    tagColor: "bg-orange-500",
    img: picuture,
    name: "Joker 500ml",
    des: "Launch your own water bottle brand. Your logo, your colors, your label — printed on our premium 500ml bottle. Min 50 cartons.",
    size: "500ml",
    pricePerBottle: 36,
    bottlesPerCarton: 12,
    get pricePerCarton() {
      return this.pricePerBottle * this.bottlesPerCarton;
    },
    minCarton: 6,
    get price() {
      return this.pricePerCarton * this.minCarton;
    },
    category: "Custom Brand",
  },
  {
    id: "cb-1500",
    brand: "Client Brand",
    brandType: "custom",
    tag: "Custom",
    tagColor: "bg-orange-500",
    img: picuture,
    name: "Joker 1500ml",
    des: "Go big with your brand. 1500ml custom bottles with full branding — ideal for retail, corporate gifting, and events.",
    size: "1500ml",
    pricePerBottle: 62,
    bottlesPerCarton: 6,
    get pricePerCarton() {
      return this.pricePerBottle * this.bottlesPerCarton;
    },
    minCarton: 6,
    get price() {
      return this.pricePerCarton * this.minCarton;
    },
    category: "Custom Brand",
  },
];

export const allProducts = [
  {
    id: "af-500",
    brandType: "own",
    category: "Own Brand",
    tag: "Our Brand",
    tagColor: "bg-sky-500",
    img: "https://placehold.co/300x300/e0f2fe/0ea5e9?text=Absolutely+Not",
    name: "Absolutely Not 500ml",
    des: "Aqua Forge's signature bottle. Crisp, clean, BPA-free with leak-proof lid. Perfect for daily hydration.",
    size: "500ml",
    pricePerBottle: 36,
    bottlesPerCarton: 12,
    pricePerCarton: 432,
    minCarton: 6,
  },
  {
    id: "af-1500",
    brandType: "own",
    category: "Own Brand",
    tag: "Our Brand",
    tagColor: "bg-sky-500",
    img: "https://placehold.co/300x300/bae6fd/0284c7?text=Absolutely+Not",
    name: "Absolutely Not 1500ml",
    des: "The big one. Extra capacity for gym, travel and long days. Same premium Absolutely Not quality.",
    size: "1500ml",
    pricePerBottle: 62,
    bottlesPerCarton: 6,
    pricePerCarton: 372,
    minCarton: 6,
  },

  // ── Client Brands ──
  {
    id: "client-001",
    brandType: "client",
    category: "Client Brand",
    tag: "Client Brand",
    tagColor: "bg-violet-500",
    img: "https://placehold.co/300x300/ede9fe/8b5cf6?text=HydraX",
    name: "HydraX 500ml",
    des: "Custom branded bottle for HydraX — a Karachi-based fitness brand. Bold identity, clean label.",
    size: "500ml",
    pricePerBottle: 36,
    bottlesPerCarton: 12,
    pricePerCarton: 432,
    minCarton: 6,
  },
  {
    id: "client-002",
    brandType: "client",
    category: "Client Brand",
    tag: "Client Brand",
    tagColor: "bg-emerald-500",
    img: "https://placehold.co/300x300/d1fae5/10b981?text=PureFlow",
    name: "PureFlow 1500ml",
    des: "Premium hydration brand for corporate offices. 1500ml with a minimal, professional finish.",
    size: "1500ml",
    pricePerBottle: 62,
    bottlesPerCarton: 6,
    pricePerCarton: 372,
    minCarton: 6,
  },
  {
    id: "client-003",
    brandType: "client",
    category: "Client Brand",
    tag: "Client Brand",
    tagColor: "bg-rose-500",
    img: "https://placehold.co/300x300/ffe4e6/be123c?text=AquaLux",
    name: "AquaLux 500ml",
    des: "Luxury matte finish bottle for AquaLux — crafted for premium gifting and high-end events.",
    size: "500ml",
    pricePerBottle: 36,
    bottlesPerCarton: 12,
    pricePerCarton: 472,
    minCarton: 6,
  },
  {
    id: "client-004",
    brandType: "client",
    category: "Client Brand",
    tag: "Client Brand",
    tagColor: "bg-amber-500",
    img: "https://placehold.co/300x300/fef3c7/d97706?text=ZenDrop",
    name: "ZenDrop 1500ml",
    des: "Earthy wellness bottle for ZenDrop — mindful hydration brand with an organic identity.",
    size: "1500ml",
    pricePerBottle: 62,
    bottlesPerCarton: 6,
    pricePerCarton: 372,
    minCarton: 6,
  },
];
